apiVersion: apps/v1
kind: Deployment
metadata:
  name: parksharing-adminclient
  namespace: parksharing
  argocd-image-updater.argoproj.io/image-list: adminclient=smixers/parksharing-admin-client
  argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parksharing-adminclient
  template:
    metadata:
      labels:
        app: parksharing-adminclient
    spec:
      containers:
      - name: adminclient
        image: smixers/parksharing-admin-client:latest
        ports:
        - containerPort: 8001
        env:
        - name: TZ
          value: "Europe/Berlin"
        - name: NODE_ENV
          value: "development"
        - name: services__adminserver__http__0
          value: "http://parksharing-adminserver:8080"
        - name: BROWSER
          value: "none"
        - name: REACT_APP_AUTH0_DOMAIN
          value: "PUT_REACT_APP_AUTH0_DOMAIN_HERE"
        - name: REACT_APP_AUTH0_CLIENT_ID
          value: "PUT_REACT_APP_AUTH0_CLIENT_ID_HERE"
        - name: REACT_APP_AUTH0_CALLBACK_URL
          value: "PUT_REACT_APP_AUTH0_CALLBACK_URL_HERE"
        - name: REACT_APP_API_SERVER_URL
          value: "./api"
        - name: REACT_APP_AUTH0_AUDIENCE
          value: "PUT_REACT_APP_AUTH0_CALLBACK_URL_HERE"
        - name: PORT
          value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: parksharing-adminclient
  namespace: parksharing
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001 # Exposing on port 30001 outside the cluster
  selector:
    app: parksharing-adminclient
