name: ci

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

  docker:
    uses: ObseumEU/github-workflows/.github/workflows/build-and-push.yml@master
    with:
      context: src/ParkSharing.Reservation.Server  # Context directory for the build
      project_file: ParkSharing.Reservation.Server.csproj  # Project file path relative to the context
      tests: false
      build_method: dotnet
      image: davidrosko/parksharing-reservation-server
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
